### ISSUE TITLE
The cursor (vertical bar) not visible when renaming a file/folder under Yaru-MATE-dark theme in Caja

### ISSUE THREAD

**Issue by navycatt** [ubuntu-mate/ubuntu-mate-artwork#82]
21.10 Ubuntu Mate, Yaru Mate Dark theme, the cursor (vertical bar) is not visible while renaming a file in Caja. Yaru Mate light is ok. See attachment.
![2022-01-20 06-16-22](https://user-images.githubusercontent.com/92228311/153713677-90b78149-bbc6-4eca-85bc-eacaaec0ea43.png)
Bugs https://bugs.launchpad.net/ubuntu/+source/ubuntu-mate-artwork/+bug/1960700 and https://bugs.launchpad.net/ubuntu/+source/ubuntu-mate-artwork/+bug/1926094

**Comment by flexiondotorg** [comment]
Fixed via 2470ec9f36ab203b01470f150354ec5a26134309 and 6c60c24da44b6468892794c53f76019e204d427c

**Comment by navycatt** [comment]
I tested ubuntu mate 22.04 with package version ubuntu-mate-artwork 22.04.1. The problem is not solved.

**Comment by navycatt** [comment]
yaru-mate-light with text cursor
![Снимок экрана в 2022-02-27 06-22-59](https://user-images.githubusercontent.com/92228311/155867037-78ab4c5c-8891-455f-ae3d-cf8c80bba830.png)

**Comment by navycatt** [comment]
yaru-mate-dark without text cursor
![Снимок экрана в 2022-02-27 06-20-33](https://user-images.githubusercontent.com/92228311/155867050-8941869d-61c0-409f-9471-2c2bf4e1a7e6.png)
